name: android_calendar_intents
description: A new Flutter package.
version: 0.0.5
homepage: https://github.com/ali2236/android_calendar_intents

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent:

dev_dependencies:
  flutter_test:
    sdk: flutter